version: '2'
services:
  projetobasemongodbgateway-mongodb:
    image: mongo:4.2.6
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/projetoBaseMongodbGateway/mongodb/:/data/db/
